using System;
using System.IO;
using System.Windows.Forms;
using System.Xml;

namespace Optoset
{
    public partial class NastaveniaForm : Form
    {

        private const string fileName = "nastavenia.xml";

        public NastaveniaForm()
        {
            InitializeComponent();
        }

        public void Initiate()
        {
            if (File.Exists(Directory.GetCurrentDirectory() + "\\data\\" + fileName))
            {
                LoadData();
            }
        }

        private void NastaveniaForm_FormClosing(object sender, FormClosingEventArgs e)
        {
            Save();
            Hide();
            e.Cancel = true;
        }

        private void Save()
        {
            if (!Directory.Exists(Directory.GetCurrentDirectory() + "\\data"))
            {
                Directory.CreateDirectory(Directory.GetCurrentDirectory() + "\\data");
            }

            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            XmlWriter writer = XmlWriter.Create(Directory.GetCurrentDirectory() + "\\data\\" + fileName, settings);

            writer.WriteStartDocument();

            writer.WriteComment("This file is generated by the program.");

            writer.WriteStartElement("nastavenia");

            writer.WriteElementString("nazov", textBox1.Text);
            writer.WriteElementString("ico", textBox2.Text);
            writer.WriteElementString("dic", textBox3.Text);
            writer.WriteElementString("icdph", textBox4.Text);
            writer.WriteElementString("adresa", richTextBox1.Text);
            writer.WriteElementString("iban", textBox7.Text);
            writer.WriteElementString("bic", textBox8.Text);
            writer.WriteElementString("register", textBox5.Text);
            writer.WriteElementString("ustav", textBox6.Text);
            writer.WriteElementString("kodPoskytovatela", textBox9.Text);
            writer.WriteElementString("registracnyKod", textBox10.Text);
            writer.WriteElementString("poplatokZaRecept", textBox11.Text);

            writer.WriteEndElement();

            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void LoadData()
        {
            var file = new XmlDocument();
            file.Load(Directory.GetCurrentDirectory() + "\\data\\" + fileName);

            var n = file.GetElementsByTagName("nastavenia");
            if (n.Count > 0)
            {
                XmlNode nastavenia = n[0];
                textBox1.Text = nastavenia.SelectNodes("nazov")[0].InnerText;
                textBox2.Text = nastavenia.SelectNodes("ico")[0].InnerText;
                textBox3.Text = nastavenia.SelectNodes("dic")[0].InnerText;
                textBox4.Text = nastavenia.SelectNodes("icdph")[0].InnerText;
                richTextBox1.Text = nastavenia.SelectNodes("adresa")[0].InnerText;
                textBox7.Text = nastavenia.SelectNodes("iban")[0].InnerText;
                textBox8.Text = nastavenia.SelectNodes("bic")[0].InnerText;
                textBox5.Text = nastavenia.SelectNodes("register")[0].InnerText;
                textBox6.Text = nastavenia.SelectNodes("ustav")[0].InnerText;
                textBox9.Text = nastavenia.SelectNodes("kodPoskytovatela")[0].InnerText;
                textBox10.Text = nastavenia.SelectNodes("registracnyKod")[0].InnerText;
                textBox11.Text = nastavenia.SelectNodes("poplatokZaRecept")[0].InnerText;
            }
        }
    }
}
